var nxSeed = 0.0; // seed for noise()
var nySeed = 0.0; // seed for noise()

function setup() {
	createCanvas(400, 400);
}

function draw() {
	noStroke();
    // draw a background wiht sme translucency
	fill(180, 180, 255, 75);
	rect(0,0, width, height);
    // draw a circle
	stroke(0);
	strokeWeight(5);
	noFill();
	ellipse(noise(nxSeed) * width, noise(nySeed) * height, 30); // draw the ellipse at a locatio generated by the noise function

	nxSeed += .01; // increment value for x
	nySeed += .005;  // increment value for y

}